Fix model, enhance administrators' power, and misc shit
CSIEHaTerX/Backend pull request #64
Opened 2023-12-19 20:50 UTC by Dragonfly911117

## Changes Made
### Fixes
- Resolved issues 
  - #40 
  - #52
  - #53 
  - #63

### API Modifications
#### PUT
- `/api/account/`: Admins empowered to update other accounts.
- `/api/coupon/`: Ability added to update coupons.
- `/api/shop/`: Admins capable of updating other shops.
- `/api/product/`: Admins granted permission to update other products.

#### GET
- `/api/account/all`: Accessible only to Admins to retrieve all accounts.
- `/api/shop/all/`: Exclusive to Admins for accessing all shops.
- `/api/shop/mine/`: Retrieve shops under the current user.
- `/api/shop/`: Now exclusively returns activated shops.
- `/api/product/all/`: Fetch all products based on specific conditions.

#### POST
- `/api/coupon`: Now requires a logged-in account (i.e., a token). Admins can create coupons for shops they don't own.
- `/api/shop/`: Admins can create shops for other accounts.

### Model Changes
- Updated time-related attributes' type to use `datetime.datetime` and `datetime.date`.
- Enforced email format validation to follow `*@*.*` format (Remove tuples that violate the format to prevent 422 errors).
- Removed `SuccessModel`.
- Renamed attribute `msg` in `ErrorModel` to `detail`.
- Introduced several new models.

### Miscellaneous
- Refactored some naming conventions.
- Optimized queries needing only one tuple by adding `LIMIT 1`.
- Enhanced error handling during development (TODO: Remove on release).
- Added utility functions.
- Changed `birthday` type in the `Account` table to `date` to align with model changes.
- Added required dependency package.

2023-12-19 20:52 UTC, Dragonfly911117 commented
中文好讀(或許吧，ChatGPT 翻譯的)版:

## 修改項目
### 修復
- 解決了問題 #40、#52、#53、#63。

### API 修改
#### PUT
- `/api/account/`: 管理員可更新其他帳戶資訊。
- `/api/coupon/`: 新增功能以更新優惠券。
- `/api/shop/`: 管理員可更新其他店家資訊。
- `/api/product/`: 管理員有權更新其他商品。

#### GET
- `/api/account/all`: 僅限管理員取得所有帳戶資訊。
- `/api/shop/all/`: 供管理員獲取所有店家資訊。
- `/api/shop/mine/`: 取得目前使用者的店家資訊。
- `/api/shop/`: 現在僅回傳啟用的店家資訊。
- `/api/product/all/`: 依特定條件取得所有商品資訊。

#### POST
- `/api/coupon`: 現在需要已登入的帳戶（即 token）。管理員可為非自己擁有的店家建立優惠券。
- `/api/shop/`: 管理員可為其他帳戶建立店家資訊。

### 模型修改
- 更新時間相關屬性的類型為 `datetime.datetime` 和 `datetime.date`。
- 強制電子郵件格式驗證為 `*@*.*` 格式（忽略違反格式的元組以避免 422 錯誤）。
- 移除 `SuccessModel`。
- 將 `ErrorModel` 中的屬性 `msg` 重新命名為 `detail`。
- 引入了幾個新模型。

### 雜項
- 重新命名某些慣用命名規則。
- 對於只需要一個元組的查詢添加了 `LIMIT 1` 以優化效能。
- 在開發期間增強錯誤處理（待完成：發布時刪除）。
- 新增實用功能函式。
- 將 `Account` 表中的 `birthday` 類型更改為 `date` 以配合模型變更。
- 新增必要的依賴套件。

2023-12-20 07:14 UTC, Vghxv requested changes

2023-12-20 07:14 UTC, Vghxv commented on app/router/account.py
> +            detail=f"Permission denied."
```suggestion
            detail="Permission denied."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/account.py
> +                detail=f"Something wrong happened."
```suggestion
                detail="No account found."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/account.py
> +            detail=f"Something went wrong."
```suggestion
            detail="Create account failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/account.py
> +                detail=f"Something went wrong."
```suggestion
                detail="Update account failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/coupon.py
> +                detail=f"Only admin can create coupon for other shops."
```suggestion
                detail="Only admin can create coupon for other shops."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/coupon.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Create coupon failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/coupon.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Update Coupon failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Create Product failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Update product failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"There is no product."
```suggestion
        detail="There is no product."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +    print(sql)
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +    print(product_form)
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
>          shop["update_time"] = str(shop["update_time"])
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +        shop["update_time"] = str(shop["update_time"])
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/coupon.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Update coupon failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"There is no product."
```suggestion
        detail="There is no product."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Create product failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +        detail=f"Something wrong happened."
```suggestion
        detail="Update product failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/product.py
> +    print(sql)
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
>          shop["update_time"] = str(shop["update_time"])
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +        shop["update_time"] = str(shop["update_time"])
```suggestion
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +        detail=f"Something went wrong"
```suggestion
        detail="Create shop failed."
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +                detail=f"Permission denied"
```suggestion
                detail="Permission denied"
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +        detail=f"Something went wrong"
```suggestion
        detail="Something went wrong"
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +                    detail=f"Permission denied"
```suggestion
                    detail="Permission denied"
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +            detail=f"Permission denied"
```suggestion
            detail="Permission denied"
```

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +            shop["update_time"] = str(shop["update_time"])
update time dont't need to cast type

2023-12-20 07:14 UTC, Vghxv commented on app/router/shop.py
> +        detail=f"No shops found"
```suggestion
        detail="No shops found"
```

2023-12-20 07:38 UTC, Vghxv approved these changes

2023-12-20 07:40 UTC, merged