Update db
CSIEHaTerX/Backend pull request #70
Opened 2023-12-21 06:21 UTC by Vghxv

## Changes Made
### Fixes
- #60 
- #65 
- #66

### API Changes
#### GET
- None

### Misc Changes
- None

2023-12-21 06:25 UTC, Vghxv commented
note : this PR will break coupon api

2023-12-21 06:50 UTC, Dragonfly911117 commented
> note : this PR will break coupon api

Why not updating them as well?

2023-12-23 09:27 UTC, Dragonfly911117 requested changes

2023-12-23 09:27 UTC, PEKKA1117 commented on app/router/coupon.py
> +            detail=f"Only admin can update coupon for other shops."
No need to use f-string here

2023-12-23 09:27 UTC, PEKKA1117 commented on app/utils/auth.py
>              account["birthday"] = account["birthday"].strftime("%Y-%m-%d")
Birthday is also in `date` type as well. This line is meaningless.

2023-12-23 09:27 UTC, PEKKA1117 commented on sql-scripts/7Comment.sql
> +        foreign key (product_uuid) references Product (product_uuid),
I thought we are commenting to orders?

2023-12-23 09:27 UTC, PEKKA1117 commented on sql-scripts/8Coupon.sql
>      shop_uuid   varchar(64)                         not null,
No `shop_uuid`s

2023-12-23 09:33 UTC, Dragonfly911117 commented on app/router/coupon.py
> +            detail=f"Only admin can update coupon for other shops."
```suggestion
detail="Only admin can update coupon for other shops."
``

2023-12-23 09:47 UTC, Vghxv commented on sql-scripts/7Comment.sql
> +        foreign key (product_uuid) references Product (product_uuid),
I changed it to product, so comment and transaction willl not functionally dependent on (transaction_uuid, account_uuid)

2023-12-23 09:49 UTC, Dragonfly911117 commented on sql-scripts/8Coupon.sql
>      shop_uuid   varchar(64)                         not null,
```suggestion
```

2023-12-23 09:50 UTC, Dragonfly911117 commented on app/utils/auth.py
>              account["birthday"] = account["birthday"].strftime("%Y-%m-%d")
```suggesion
        account = result[0]
```

2023-12-23 10:16 UTC, Vghxv commented on sql-scripts/8Coupon.sql
>      shop_uuid   varchar(64)                         not null,
not reload datagrid before export@@

2023-12-23 10:34 UTC, Dragonfly911117 approved these changes
LGTM

2023-12-23 10:35 UTC, merged