Comment
CSIEHaTerX/Backend pull request #87
Opened 2023-12-25 13:47 UTC by Vghxv

## Changes Made
### Fixes
- issue #84
- issue #55 

### API Changes
GET
- /api/comment
POST
- /api/comment
PUT
- /api/comment
GET
- /api/comment/guest

### Misc Changes
update comment table 
add HateList table

2023-12-25 13:59 UTC, Dragonfly911117 requested changes

2023-12-25 13:59 UTC, Dragonfly911117 commented on sql-scripts/7Comment.sql
> +    dislikes     int       default 0                 not null,
There's no need to record these as we can get them via counting HateLists

2023-12-25 13:59 UTC, Dragonfly911117 commented on app/model/comment.py
> +    is_mine: int
Doesn't fit db schema? (product_uuid is missing)
```sql
  comment_uuid varchar(64)                         not null
        primary key,
    product_uuid varchar(64)                         not null,
    account_uuid varchar(64)                         not null,
    text         varchar(512)                        not null,
```

2023-12-26 09:04 UTC, Vghxv commented
re PR in  #88

2023-12-26 09:04 UTC, closed without merging