Transaction fix
CSIEHaTerX/Backend pull request #99
Opened 2023-12-30 14:54 UTC by Dragonfly911117

## Changes Made
### Fixes
- #91 

### API Changes
#### GET
- `/api/transaction`: Now returns in 
```json
{
  "transactions": [
    {
      "transaction_uuid": "string",
      "account_uuid": "string",
      "shop_uuid": "string",
      "discount": 0,
      "receive_time": "2023-12-30T14:36:31.844Z",
      "status": "Ordered",
      "order_time": "2023-12-30T14:36:31.844Z",
      "products": {
        "transaction_product_logs": [
          {
            "product_name": "string",
            "product_uuid": "string",
            "product_description": "string",
            "quantity": 0,
            "price": 0
          }
        ]
      },
      "total_price": 0
    }
  ]
}
```
- `/api/transaction/all`: As `/api/transaction`

#### POST
- `/api/transaction/all`: Now does NOT allow admins to force others to buy thing

### Misc Changes
- Add a few tuples in transaction-related tables
- Ensure that creating a transaction is an atomic action.

2023-12-31 03:32 UTC, Vghxv requested changes

2023-12-31 03:32 UTC, Vghxv commented on app/router/transaction.py
transaction PUT and POST lacks as_form

2024-01-01 02:37 UTC, garry911128 approved these changes

2024-01-01 09:38 UTC, Dragonfly911117 commented on app/router/transaction.py
The intention behind avoiding the use of `as_form` in the POST API is due to the transaction encompassing multiple products. Regarding the PUT API, I've implemented updates—take a look.

2024-01-01 09:57 UTC, Vghxv approved these changes
lgtm

2024-01-01 09:58 UTC, merged